# Generated by Django 4.1.2 on 2022-11-05 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_db', '0003_alter_categories_options_testdata_mayor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='mayor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mayor_cities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TestDataRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('city_on_bookmarks', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_db.testdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='testdata',
            name='citizen',
            field=models.ManyToManyField(related_name='citizen_cities', through='test_db.TestDataRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
