# Generated by Django 4.1.2 on 2022-11-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0004_alter_testdata_mayor_testdatarelation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdatarelation',
            options={'verbose_name': 'Оценка пользователя', 'verbose_name_plural': 'Оценки пользователя'},
        ),
        migrations.AddField(
            model_name='testdatarelation',
            name='rate',
            field=models.CharField(choices=[(1, 'fine'), (2, 'good'), (3, 'amazing')], default=3, max_length=9),
        ),
    ]
